### ISSUE TITLE
internal/change java in XSL files to pure XSL where possible

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/DSpace#108]
OAI formats in /dspace/config/crosswalks/oai/metadataFormats use java (those which are imported from clarin).
Try and change as many of them as possible into pure XSL, possibly all of them.

(Java implementations can be found [here](https://github.com/dataquest-dev/DSpace/tree/feature/pid-3-return-directly-cmdi/dspace-oai/src/main/java/org/dspace/xoai/services/impl/resources/functions) )

**Comment by milanmajchrak** [comment]
Done without pure XSL

**Comment by milanmajchrak** [comment]
Done without pure XSL
