### ISSUE TITLE
internal/editing-item-license-not-loaded

### ISSUE THREAD

**Issue by MajoBerger** [dataquest-dev/DSpace#185]
- license and possibly other during workflow submission in UI
- good luck

**Comment by milanmajchrak** [comment]
> * license and possibly other during workflow submission in UI
> * good luck

### Problem description:
If the submitter tries to edit the item the bitstream license is not loaded.

**Comment by milanmajchrak** [comment]
The problem: the licenses weren't properly initialized from BE, they were initialized from local JSON.
