### ISSUE TITLE
feature/se-9-upload CMDI

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#19]
## Problem description
For the admin must be a option to upload CMDI file in the Submission UI. The CMDI file must be stored in the:
1. METADATA bundle - the admin has selected the option to upload the CMDI file
2. ORIGINAL bundle - the hasn't selected the option to upload the CMDI file

- [x] Define a new local metadata type hasCMDI
- [x] Create a test for a new local metadata
- [x] Define a new input field (checkbox) for the admin - is uploading a cmdi file.
- [x] Every file will be pushed to the bundle ORIGINAL then the CMDI file will be moved to the METADATA bundle by the MetadataValidation class.
- [x] If the user is admin and has selected option to upload CMDI file, the CMDI file must be stored in the bundle METADATA. If the user hasn't selected option to upload CMDI file but is uploading the CMDI file, the CMDI file must be stored in the bundle ORIGINAL. This check will be done by the MetadataValidation in the method of the new class _CMDIFileBundleMaintainer.updateCMDIFileBundle_.
- [x] Create a test for uploading CMDI file.
- [x] Create a tests for maintaining CMDI file in the correct bundles.

### How to test:
- [x] Admin should see a new input field: _Has CMDI file_
- [x] User shouldn't see a new input field: _has CMDI file_
- **For admin:**
- **With CMDI file**
- [x] Normally create a new Item with the file -> After depositing the file should be seen in the _Files_ section in the Item View page.
- [x] Create a new Item with the file but mark _Has CMDI file_  checkbox to "Yes" and deposit new Item. -> After depositing you shouldn't see the file in the _Files_ section in the Item View.
- [x] Create a new Item -> mark _Has CMDI file_ to "Yes" and upload file. -> remove file -> unmark _Has CMDI file_ -> again upload file and mark _Has CMDI file to "Yes". Then deposit Item and the file shouldn't be seen in the Item View in the Files section.
- **NO CMDI file (some normal file)**
- [x] Normally create a new Item with file -> Deposit -> the file should be seen in the File section in the Item View.
- [x] Create a new Item with file -> mark _Has CMDI file_ to "No" -> the file should be seen in the Files section in the Item View.
- **For user:**
- [x] Normally create a new Item with CMDI file -> the file should be seen in the Files Section in the Item View page.
- [x] Normally create a new Item with NO CMDI file -> the file should be seen in the Files Section in the Item View page.

**Comment by Paurikova2** [comment]
- it is possible to edit metadata informed if file is cmdi or not by admin
- there is no information in metadata that file is not cmdi
- there is no check if file is really cmdi when user marks "Has CMDI file"
- there is no option to mark the file as cmdi after deposit
- cannot **delete** cmdi file when "Has CMDI file" is marked - the same behavior with bitstream file

**Comment by milanmajchrak** [comment]
@Paurikova2 
- Yes, if the admin edit hasCMDI in the metadata it is his mess
- It is ok that user do not know about cmdi file - cmdi file is not standard file and there is no need to have information that the item doesn't have cmdi file
- That check is unnecessary
- Yes, the admin must be careful when is creating the Item with CMDI

**Comment by milanmajchrak** [comment]
@Paurikova2 The CMDI file should be possible to remove - test it again please

**Comment by Paurikova2** [comment]
- It is not possible to upload one cmdi file as "Has CMDI file" and another cmdi file as no "Has CMDI file"

**Comment by Paurikova2** [comment]
@milanmajchrak 
It is possible to remove CMDI file (bitstream).

**Comment by milanmajchrak** [comment]
> * It is not possible to upload one cmdi file as "Has CMDI file" and another cmdi file as no "Has CMDI file"

It is ok

**Comment by milanmajchrak** [comment]
Tested
