### ISSUE TITLE
Prepare estimate ...

### ISSUE THREAD

**Issue by mrovnanik** [dataquest-dev/DSpace#197]
... for having this page as home-page in our version:
![image](https://user-images.githubusercontent.com/14863763/216299783-2203f062-7e91-497a-ba79-4bcfa6bde2cc.png)

**Comment by milanmajchrak** [comment]
HomePage for mobile devices: 
- ![image](https://user-images.githubusercontent.com/90026355/216313022-d229b1a5-7b62-4f8e-908f-1f74c7a822ad.png)
- ![image](https://user-images.githubusercontent.com/90026355/216313055-59194756-e1fe-42f1-9ba0-47b07b0fb6d9.png)

**Comment by milanmajchrak** [comment]
I guess that estimates were finished.
