### ISSUE TITLE
Cleanup installation guides (wiki, readme, ...)

### ISSUE THREAD

**Issue by mrovnanik** [dataquest-dev/DSpace#288]

**Comment by milanmajchrak** [comment]
@MajoBerger Is it finished? Please could you describe what you have done? Ideal with links, thank you.

**Comment by MajoBerger** [comment]
Mainly reorganized tutorials.
All the links can be found in [wiki of this repo](https://github.com/dataquest-dev/DSpace/wiki#about-the-composition-of-this-project).
Overview and description is also there.
