### ISSUE TITLE
Find the easiest way for us to test S3 storage with DSpace 7.5

### ISSUE THREAD

**Issue by mrovnanik** [dataquest-dev/DSpace#289]
We must be prepared to test functionality of version 7.5 to work with S3 storage. I expect you to find the easiest solution for us that will enable us to work with S3.

@MajoBerger  START WITH AZURE. Does Microsoft offer S3?

**Comment by MajoBerger** [comment]
S3 is tested and works. We just need to find the best way to demonstrate it to interested parties.
