### ISSUE TITLE
internal/review whole wiki and remove sensitive information

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#394]
## Problem description
Maybe we keep some sensitive information in our wiki -> remove it

**Comment by milanmajchrak** [comment]
I think GA property could be commented out.

**Comment by MajoBerger** [comment]
Removed (but it's still in wiki's history. Where is it from, do we need to purge it?).
Plus what about other issues, namely the yellow one, which is weird?

Should we ignore for now?

**Comment by milanmajchrak** [comment]
Yes, we could ignore it. Could be  this issue closed?
