### ISSUE TITLE
dc.date.issued is removed and it is missing in crosswalks

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#461]
## Problem description
If the Item has `local.approximateDate` the `dc.date.issued` value is removed, because we do not want to store duplicate values in the metadata, but because of that the OAI cannot retrieve that value from `dc.date.issued`.

TODO:
Add first value from local.approximateDate.issued into `dc.date.issued` instead of removing it.

2024/Apr/17 call:
- maybe having unvalid characters like `????` in the data.issued causes some problem which OK is going to discover
- instead of removing `dc.date.issued` copy the value from the `local.approximateDate.issued` into it
- TODO: Update view in the Item View Page - do not show date if there is some value in the `local.approximateDate.issued`

2024/Apr/18:
- check conversation: https://github.com/dataquest-dev/DSpace/issues/461#issuecomment-2061278538

**Comment by milanmajchrak** [comment]
@kosarko Ďakujem za info.
1. Suhlasim, neskôr by to mohlo spôsobiť ďalší problem
2. Neviem prečo tento error nevyskakoval vo v7
3. Takže, ak su v `local.approximateDate.issued` normalne hodnoty napr: `1938, 1932, 1945`, tak do `dc.date.issued` da najvyssi datum `1945`.

Upravim to tak, že sa `dc.date.issued` nebude mazať a na FE bude nejake IF, ktore spravne zobrazi datum.

**Comment by kosarko** [comment]
@milanmajchrak 
>Takže, ak su v local.approximateDate.issued normalne hodnoty napr: 1938, 1932, 1945, tak do dc.date.issued da najvyssi datum 1945.
To ale jenom pokud je dc.date.issued 0000?

**Comment by milanmajchrak** [comment]
> @milanmajchrak
> 
> > Takže, ak su v local.approximateDate.issued normalne hodnoty napr: 1938, 1932, 1945, tak do dc.date.issued da najvyssi datum 1945.
> > To ale jenom pokud je dc.date.issued 0000?

Áno, dobrá poznámka.
