### ISSUE TITLE
Dependencies were used from DSpace, they changed, our build failed (they removed git)

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#466]
https://github.com/DSpace/DSpace/commit/538833f8a8573e55b49cb28ee6bfbc5330ad6bc4#diff-39dec157e9f52bfc7b0fdf58b66b346b3a9039099663725a13b4b4ce446dafd1

removed git dependency, but our maven currently needs it, so we were unable to push images.

**Comment by MajoBerger** [comment]
Merged to all deploy branches. (Since without this change, no build can succeed.)
