### ISSUE TITLE
data inconsistency after migrate - check the search page results

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#555]
_Spinoff issues were made_
 

- [x] - [x] Import a new dump - there are errors (https://github.com/dataquest-dev/dspace-angular/actions/runs/8328732190/job/22790594769)
- [x] Check results from a search
- [x] Check Item's metadata fields
- [ ] Automatically check logs after migration (github action logs)

**Comment by MajoBerger** [comment]
could this be a bit more specific please?

**Comment by milanmajchrak** [comment]
The search results are not met:
v5:
![Image](https://github.com/dataquest-dev/DSpace/assets/90026355/85a64743-d348-43bd-be59-4cc8ce30109a)

v7:
![Image](https://github.com/dataquest-dev/DSpace/assets/90026355/d4930fc8-42db-4f63-905c-43589996e12e)

**Comment by milanmajchrak** [comment]
v5:
![Image](https://github.com/dataquest-dev/DSpace/assets/90026355/7edc0c92-7dc3-4b8b-8ccd-bc3f25ad69c2)

v7:
![Image](https://github.com/dataquest-dev/DSpace/assets/90026355/19d7a3db-fb01-4401-bc70-bd540ca92b27)

**Comment by MajoBerger** [comment]
This will always throw an error
https://github.com/dataquest-dev/dspace-python-api/blob/d2560ed359418565b1ae0a96e27c4e363259fe75/src/dspace/_rest.py#L260

https://github.com/dataquest-dev/dspace-python-api/blob/d2560ed359418565b1ae0a96e27c4e363259fe75/src/dspace/_rest.py#L392

len of None -> error

**Comment by MajoBerger** [comment]
older versions are not shown in search, e.g. Akces 2:


![Image](https://github.com/dataquest-dev/DSpace/assets/88670521/0c4e502b-e81c-4e77-a109-4595e9bea991)

https://lindat.mff.cuni.cz/repository/xmlui/handle/11858/00-097C-0000-0019-89A0-9
https://dev-5.pc:8443/items/c4b3ffef-a486-48a1-b886-44d4b973837e exists, but is not shown in search = resulting in different numbers.

**Comment by MajoBerger** [comment]
Many errors similar to this:


![Image](https://github.com/dataquest-dev/DSpace/assets/88670521/93324306-f54f-4271-b2aa-6ccad48c5000)

I don't understand what this means, the link is not even in ufal clarin


![Image](https://github.com/dataquest-dev/DSpace/assets/88670521/ad688e9e-9ab8-46a5-a55b-46ad2d869c4a)

http://hdl.handle.net/20.500.11956/174483
