### ISSUE TITLE
OAI: elg crosswalk - langUtil with real iso 693 data, get shortest lang id

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#586]
- [ ] There is also missing whole elg.xsl crosswalk: Original issue: https://github.com/ufal/clarin-dspace/issues/1029
- [ ] There is some schema which prefers 2 letters code instead of 3 letters..

**Comment by kosarko** [comment]
`ufal-showstopper` potrebujeme elg crosswalk

@vidiecan trocha kontextu: elg jako schema je nastupce metashare

**Comment by milanmajchrak** [comment]
@Paurikova2 Write Python tests to test this crosswalk
