### ISSUE TITLE
Importing - 88: A new bitstreams are not sync with S3 - why?

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#597]
Importing creates only Bitstream object with the metadata - synchronization with S3 must be done in other way.

**Comment by MajoBerger** [comment]
When dump is imported, files are stored directly in `/dspace/assetstore` inside the container. 
Therefore, from the point of view of python script import, they are already there. They are not uploaded by REST API.
Therefore, it makes sense that files are not in S3.

This behavior is expected and there is nothing wrong with this.
