### ISSUE TITLE
Matomo Statistics - use handle in the URL (DSpace7 has UUID)

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#607]

**Comment by kosarko** [comment]
na tohle jsem dneska zapomnel. Tohle se tyka item views, tedy trackovani z FE?

**Comment by milanmajchrak** [comment]
Rozmýšľam, čo sme chceli touto issue povedať, lebo pri trackovani Matomo requestu sa nepouživa žiadny item/bistream uuid, ani vo v5, ani vo v7. 
Nemysleli sme to, že pri logovani štatistik pri sťahovani bistreamov namiesto uuid logovat handle?

**Comment by kosarko** [comment]
co posila FE jako pageview? je tam handle nebo uuid? v5 podle me brala url (kterou vidim v browseru) a ta byla `xmlui/handle/xxx/yyy`, takze pak muzu nejak v matomu delat pageviews per handle...

co posila BE?

**Comment by milanmajchrak** [comment]
Už rozumiem. Matomo netrackuje FE requesty, na to tam maju google analytics a na FE sme Matomo neriešili.

Matomo trackuje na BE iba 
- bitstream downloads: dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java 
- oai requests: dspace-oai/src/main/java/org/dspace/xoai/controller/DSpaceOAIDataProvider.java

**Comment by kosarko** [comment]
On je tracking-code pro matomo v (lindat-common) footeru, akorat nevim, jestli to tam zustalo i v te dspace verzi a jestli to trackuje neco rozumneho, nebo jestli to udela jen jeden hit pri nacteni footeru. To je jedna cast, druha je, ze by asi bylo lepsi v matomo videt handles nez uuids...

Ad BE tohle https://github.com/dataquest-dev/DSpace/blob/8d115daea75b9586248aab4359b6b6f28a78a980/dspace-api/src/main/java/org/dspace/app/statistics/clarin/ClarinMatomoTracker.java#L101-L108 vypada lehce podivne...vsechno `setHeaderUserAgent`?

**Comment by milanmajchrak** [comment]
1. Piwik je vo footeri, len posiela requesty na lindat, dalo by sa to updatnut znova moutnutim footeru.
2. Rozumiem, vieme zmenit UUID na handle, ale je tam problem, ze by sa tym padom zmenila cela URL. Nebude lepšie spraviť to cez segmenty? Žeby som pridal handle ako Custom Variable do Matomo requestu.
3. Tak ten `setHeaderUserAgent` je chyba, fixnem to. Ďakujem za upozornenie

**Comment by kosarko** [comment]
>Rozumiem, vieme zmenit UUID na handle, ale je tam problem, ze by sa tym padom zmenila cela URL. Nebude lepšie spraviť to cez segmenty? Žeby som pridal handle ako Custom Variable do Matomo requestu.

segmenty za me nejsou dobra volba viz ufal/DSpace#957, tam linknuta debata a zejmena
>we changed how segments work in 3.12.0, now when you select visits based on a page url, it will return all visits and all page urls these visits did.

nebo https://matomo.org/faq/general/how-do-segments-work-when-segmenting-on-specific-actions-pages-or-events-and-how-do-i-filter-out-any-actions-that-dont-match/

custom variables taky nevypada jako spravna cesta. https://plugins.matomo.org/CustomVariables:
> This feature used to be part of Matomo. However, we no longer plan to further develop custom variables and only fix important bugs or security issues and we might stop supporting Custom Variables in the future.
We therefore highly recommend using [Custom Dimensions](https://matomo.org/docs/custom-dimensions/) instead which is directly available within your Matomo

Custom Dimensions maybe...zkusim se na to podivat

**Comment by kosarko** [comment]
custom dimensions po kratkym pokusu vypada, ze by melo byt pouzitelny...

**Comment by milanmajchrak** [comment]
Je potrebne upraviť footer, aby trackoval správne UI events - vyskúšať pridať posielanie Matomo requests v onInit metode. Ako sa to bude správať pri SSR?

**Comment by kosarko** [comment]
Videl jsi tohle?
>Supporting analytics services other than Google Analytics
This project makes use of [Angulartics](https://angulartics.github.io/angulartics2/) to track usage events and send them to Google Analytics.

>Angulartics can be configured to work with a number of other services besides Google Analytics as well, e.g. [Piwik](https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/piwik), [Google Tag Manager](https://github.com/angulartics/angulartics2/tree/master/src/lib/providers/gtm), or [Azure Application Insights](https://azure.microsoft.com/en-us/services/application-insights/) to name a few.

>In order to start using one of these services, select it from the [Angulartics Providers page](https://angulartics.github.io/angulartics2/#providers), and follow the instructions on how to configure it.

>The Google Analytics script was added in [main.browser.ts](https://github.com/DSpace/dspace-angular/blob/ff04760f4af91ac3e7add5e7424a46cb2439e874/src/main.browser.ts#L33) instead of the <head> tag in index.html to ensure events get sent when the page is shown in a client's browser, and not when it's rendered on the universal server. Likely you'll want to do the same when adding a new service

z https://github.com/DSpace/dspace-angular/blob/main/docs/Configuration.md

**Comment by milanmajchrak** [comment]
Updated wiki: https://github.com/dataquest-dev/DSpace/wiki/Start-Matomo
