### ISSUE TITLE
Confirm that cmdi file is returned when the HTTP-accept header has “application/x-cmdi+xml”

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#611]
TODO:
- we need to have some Item with CMDI file - maybe it could be added into python import script?

**7. Persistent Identifiers - Centres need to associate PIDs (handles or DOIs) with their metadata records.**
- it redirects to a CMDI file for the HTTP-accept header “application/x-cmdi+xml”
- it redirects to an HTML file when accessing it from a browser
Individual files (e.g. a text, zip or sound file) can be referred to with either the handle of
the describing metadata record in combination with a part identifier11 or with another
handle.

**Comment by MajoBerger** [comment]
Works on port 88 with good nginx
`curl -k http://dev-5.pc:88/handle/11234/1-5438 -L -H "Accept: application/x-cmdi+xml"`

does not work on bad nginx
`curl -k https://dev-5.pc:8443/handle/11234/1-5438 -L -H "Accept: application/x-cmdi+xml"`

It is because of nginx directive

```nginx
if ($query_string ~* "format=cmdi"){
                rewrite ^/(.*)handle/(.*)$ http://$http_host/server/cmdi/oai-metadata?metadataPrefix=cmdi&handle=$2? redirect;
            }
            if ($http_accept ~ "(.*cmdi.xml*)"){
                rewrite ^/(.*)handle/(.*)$ http://$http_host/server/cmdi/oai-metadata?metadataPrefix=cmdi&handle=$2? redirect;
            }

```

which IS in wiki. (and enables other header values, since regex is used, and  other kind of links as well
`curl -k http://dev-5.pc:88/handle/11234/1-5438?format=cmdi -L`
)

**Comment by MajoBerger** [comment]
add commands to check to Wiki

**Comment by MajoBerger** [comment]
add to 8443 nginx as well

**Comment by milanmajchrak** [comment]
Some Item could have specific CMDI file - during creation the admin upload a cmdi file which will be returned. He need to click on `Has CMDI` checkbox. Confirm that specific cmdi file is returned.

**Comment by milanmajchrak** [comment]
@MajoBerger 
https://github.com/dataquest-dev/DSpace/blob/dtq-dev/dspace-server-webapp/src/main/java/org/dspace/app/rest/CMDIRestController.java
- Return uploaded CMDI file from the CMDI bundle if:
1. The Item has metadata `local.hasCMDI = yes`
2. The Item has file in the CMDI bundle

**Comment by MajoBerger** [comment]
waiting for tests and then review

**Comment by MajoBerger** [comment]
Done, works, added to wiki etc.

**Comment by milanmajchrak** [comment]
Where in the wiki? Post a link here pls

**Comment by MajoBerger** [comment]
https://github.com/dataquest-dev/DSpace/wiki/Installation#check
