### ISSUE TITLE
OAI-PMH: Don’t expose certain col/com in oai results

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#618]
Do not expose this: https://github.com/ufal/clarin-dspace/commit/ebe982901ba25cd5be468b95dfec8560f694a0ec

It should be fixed here: https://github.com/dataquest-dev/DSpace/pull/631/files#diff-0c7ed1579d5c3017ecfe8e1101395a1b797a5016b6b8fae733ee776a01130a5eR598-R610
but it must be tested.

2024/May/21:
Tested - but it is not working properly, issue described here: https://github.com/dataquest-dev/DSpace/issues/664

**Comment by MajoBerger** [comment]
clariah submission, teaching materials =  not seen on clarin, should not be on dev5, find out why

**Comment by milanmajchrak** [comment]
Tested - but it is not working properly, issue described here: https://github.com/dataquest-dev/DSpace/issues/664
