### ISSUE TITLE
internal/Run tests in the InteliJ

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#70]
Test _patchAddMoreNonEUAndEUAndReplaceEachOtherOnItemStillInSubmissionTest_  could be run from the cmd by the command:  `mvn install -DskipIntegrationTests=false -Dit.test=org.dspace.app.rest.WorkspaceItemRestRepositoryIT.java#patchAddMoreNonEUAndEUAndReplaceEachOtherOnItemStillInSubmissionTest -DfailIfNoTests=false -Dtest.argLine=-Xmx1024m -DfailsafeJacoco=-XX:MaxPermSize=256m` 

This test should be run by the InteliJ by clicking on this icon: 
![image](https://user-images.githubusercontent.com/90026355/175959007-71ea3c3c-30cf-4557-b734-8c262f73518b.png)

**Comment by MajoBerger** [comment]
It appears this cannot work. 
I recommend making run configuration and pasting the command there, especially when multiple runs are expected.
![image](https://user-images.githubusercontent.com/88670521/176416324-c829bd4c-7ff1-49b5-840f-c513b3159c9b.png)
I wrote to slack, don't expect helpful answer tho.

**Comment by MajoBerger** [comment]
Impossible to do, was replaced by .bats in https://github.com/dataquest-dev/DSpace/issues/85
