### ISSUE TITLE
Update logging of downloading files

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#704]
Original issue: https://github.com/ufal/clarin-dspace/issues/1121

**Comment by Paurikova2** [comment]
point 1: done
point 2: done
point 3: I think it should end up in file_downloads.log because in that file we log general bitstream download information and that information is logging in this file too - we use the same variable.

**Comment by milanmajchrak** [comment]
3: It goes into file downloads log
