### ISSUE TITLE
internal/do not load test environment from the .m2 local repository

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#71]
The test environment is generated to the test-environment.zip: 
![image](https://user-images.githubusercontent.com/90026355/175959973-cd614d92-9e6f-4814-8549-1d12d19425cd.png)

After running the test, the test-environment.zip is loaded from the .m2 local repository. It mustn't be loaded from the .m2 but from the /target folder, because after command: mvn package the test env is created to the /target.

**Comment by MajoBerger** [comment]
Please when next it happens run the same command
mvn instal ... > out.txt
and send the out.txt to gather new information
[del.txt](https://github.com/dataquest-dev/DSpace/files/9009959/del.txt)
