### ISSUE TITLE
Cannot create a new version because an owningCollection is null

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#728]
When click on `Deposit` during creating a new version of the Item this error occurs: 

![Image](https://github.com/user-attachments/assets/0df38c7c-ee26-4898-b4a1-4cf164f1efad)

**Comment by milanmajchrak** [comment]
This error occurs only for imported Items.

**Comment by milanmajchrak** [comment]
It is not happening for all Items, I discovered it happened for this Item: `De Latinae Linguae Reparatione treebank`. The `owning_collection` is not assigned for the new Version, why?

**Comment by milanmajchrak** [comment]
De Latinae Linguae Reparatione treebank

owningCollection" 'd02feb03-354e-438c-8d7c-2a3f6fd779eb'

**Comment by milanmajchrak** [comment]
org.dspace.xmlworkflow.XmlWorkflowServiceImpl#226 is not executed

**Comment by Paurikova2** [comment]
We cannot create a new version of the item that owns the collection in the cwf_collectionrole table - editor.
