### ISSUE TITLE
feature/pid-5-manage-handle-table

### ISSUE THREAD

**Issue by mrovnanik** [dataquest-dev/DSpace#75]
DSpace-Clarin PID wiki - this functionality should be implemented in the DSpace7: https://github.com/dataquest-dev/DSpace/wiki/Submission-extensions

### How to test
- [x] When you log in as admin you should see the Manage Handle option in the left side menu.
- [ ] When you are not signed in or you are an user you should not see Manage Handle option in the left side menu.
- [x] Click on that icon and you should be redirected to the page `/handle-table`
- [x] `/handle-table` page should consist of Handle table section and the Change global prefix section
- [x] You should see the buttons: `New external handle`, `Edit handle`, `Delete handle`
- [x] You should be able to select some handle and click on `Delete handle` button then the table should be refreshed and the removed handle shouldn't be in the handle table
- [x] When you select some handle and click on the button `Edit handle` you should be redirected to the `/edit-handle` page and you should see the input fields and `Archive handle` checkbox.
- [x] If you edit Internal handle you should not see the `Url` input field but if you edit External handle you could be able to type the new URL
- [x] Try to edit some handles
- [x] When you click on the button `New external handle` you should be redirected to the `/new-handle` page
- [x] The `/new-handle` page should consist of input fields: `Url` and `Handle`. When you fill in some Handle data and click to `Submit` button you should be redirected to the `/handle-table`
- [x] Try to create some handles
- [x] When you click on the button `Change handle prefix` you should be redirected to the `/change-handle-prefix` page and you should see two input fields: `Old prefix` and `New prefix` when you fill in the data and click on `Submit` button you should be redirected to the `/handle-table` page and the Handle prefixes should be changed.
- [x] When you archive some Handle the old handle should be stored in the metadata `dc.relation.other`
- [x] After every operation you should see the notifications
- [x] Try to filter Handles by the Search panel
- [x] Try to break it down

### TO DO
- [x] create HandleRestRepository, inspiration: https://github.com/dataquest-dev/DSpace/blob/dtq-dev/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataFieldRestRepository.java
- [x] create HandleRest - it is wrapper for the Handle class to send it through the REST API, inspiration: https://github.com/dataquest-dev/DSpace/blob/dtq-dev/dspace-server-webapp/src/main/java/org/dspace/app/rest/model/MetadataFieldRest.java
- [x] create HandleRestConverter - this converter converts Handle to the HandleRest, inspiration: https://github.com/dataquest-dev/DSpace/blob/dtq-dev/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/MetadataFieldConverter.java
- [x] create HandleRestRepositoryIT to test APIs, inspiration: https://github.com/dataquest-dev/DSpace/blob/dtq-dev/dspace-server-webapp/src/test/java/org/dspace/app/rest/MetadatafieldRestRepositoryIT.java
- [x] create HandleResource, inspiration: https://github.com/dataquest-dev/DSpace/blob/dtq-dev/dspace-server-webapp/src/main/java/org/dspace/app/rest/model/hateoas/MetadataFieldResource.java

During implementation was nesseccary:
- [x] created HandleClarinService
- [x] created HandleClarinServiceImpl

Methods in the HandleRestRepository:

- [x] findOne - return handle in the format: 
![image](https://user-images.githubusercontent.com/90026355/176433682-3b40d382-7e7d-43e7-add4-827f6c244cca.png)
- [x] findAll - return all handles
- [x] edit one handle by id
- [x] delete one handle by id
- [x] create a new handle
- [x] change handle prefix - update on the table
- [x] fix loading values from operations
- [x] @milanmajchrak add URL column to Handle table
- [x] @Paurikova2  add URL attribute to the Handle object (do not forget for HandleRest, Converter...)
- [x] @Paurikova2 In the _findAll_ method return the handles ordered by ID.
- [ ] @milanmajchrak In FE table, the handles are unsorted (problem with JSON).
- [x] @Paurikova2 HandleRestRepository: I updated create method to createAndReturn. Get Handle from request, create a new handle and update saved handle in the same like in the ItemRestRepository or MetadataFieldRestRepository.
- [x] @Paurikova2 Update patch request: there should be option to archive old Handle.handle of the changed handle.
- [x] tests
- [x] @Paurikova2 edit handle url
- [x] @milanmajchrak error message when you set prefix - because you are sending a non-existent handle id (0). After tghe patch method there is call findOne. The problem is when you set prefix when table is empty. Maybe set patch to post.
- [x] @milanmajchrak sorting - Sort algorithm for adding new handle into handle table on end (or beginning). Now is hart to find new or modified handle.
- [x] @milanmajchrak frontend for internal handles
Remove URL:
![image](https://user-images.githubusercontent.com/107862249/185908913-fe2c59eb-15e2-492d-8ba1-c94f57156a33.png)
Load all prefixes:
Get all handle prefixes: return configService.getArrayProperty("handle.prefix"); Return value: String[]
![image](https://user-images.githubusercontent.com/107862249/185909188-948bd941-5fcb-476f-beba-2f4050a20f1a.png)
- [x] Incorrect handle in url in Communities and in Collections after changing prefix or handle:
Backend: findbyID 
Frontend: it loads it only one time and saves it into attribute
![image](https://user-images.githubusercontent.com/107862249/185909914-d417227c-65c6-423b-b67b-1b9d0338b907.png)
- [x] @Paurikova2  @milanmajchrak edit methods and attributes names 
- [x] @Paurikova2 add clarin license

**Comment by Paurikova2** [comment]
@milanmajchrak 
patch operation /replaceHandle is renamed to /updateHandle

**Comment by Paurikova2** [comment]
Testing:
Admin:
Search panel - does not work
- you have to click outside of searching box if you wanna see correct results (and it does not work all the time too)
- does not search between external handles

- when I delete handle, should I see item which had that handle in repository?

Editing handle:
- archiving does not work, but there is success message
- does not see changes after editing internal handle, but there is success message

- maybe there is not necessary message about long loading after archiving

Changing prefix:
- archiving does not work in all cases, sometimes it misses some handles
- after changing prefix I cannot see handle of new created item

User:
- there is option manage handle in menu

**Comment by Paurikova2** [comment]
Future: use similar formular for creating and editing handle like in licenses

**Comment by Paurikova2** [comment]
For future improvements:
@milanmajchrak 

Create external handle:
- the required fields are not red when user doesn't enter their values
- when user enter incorrect values, he is redirect to main page of handle (in other cases of handle work he is not redirect)
- there is error without timelap when user enter incorrect values
- when I create handle with existing handle, there is unreadable error

Edit:
- Shouldn't be button `New extended handle` readable when is some check box checked?
- when you edit handle with similar values, there is success message. Maybe there is more better some info, that you didn't change any value
- the required fields are not red when user doesn't enter their values
- when I edit handle by existing handle, there is unreadable error
- maybe some info about archive

Delete:
- there is no option to delete more handles by one click on button delete
Set prefix:
- maybe some info about archive
- there is message about long archiving when user enter incorrect values
- when user enter incorrect values, there is unreadable error
- there is error without timelap when user enter incorrect values

Searching:
- it is not intuitive how it works

**Comment by Paurikova2** [comment]
@milanmajchrak 
Set global prefix should work other: you shouldn't enter oldprefix, there should be list of used prefix
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/107862249/193781554-82fa3cf3-a77d-4e15-8b5d-2327bb5c5976.png)
