### ISSUE TITLE
feature/se-6-openaire-oaipmh-harvestability

### ISSUE THREAD

**Issue by mrovnanik** [dataquest-dev/DSpace#78]
Implement functionality that will allow (OpenAIRE related) data to be harvested via OAI-PMH interface

**Comment by MajoBerger** [comment]
@mrovnanik I need more specific info. I can edit crosswalks now and only show data based on condition. 
I also need to know where to find "funding" field.

**Comment by MajoBerger** [comment]
Testing cannot be implemented yet, I am trying to get some support on slack:
https://dspace-org.slack.com/archives/C3N0VHT6K/p1657629199361589 and https://dspace-org.slack.com/archives/C3SG47SGY/p1657708254443379
Responses are usually when I am not in work, so it's going slow, but not taking a lot of time. 
(I try something, write to slack, wait till next day for response, try something else, write again, cycle repeats.)

**Comment by milanmajchrak** [comment]
The feature was developed here: https://github.com/dataquest-dev/DSpace/issues/134
