### ISSUE TITLE
Submission workflow update

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#800]
![Image](https://github.com/user-attachments/assets/2ba51bbf-82d7-4f40-95cf-3c88910306e3)

**Comment by milanmajchrak** [comment]
https://github.com/dataquest-dev/dspace-customers/issues/150

**Comment by milanmajchrak** [comment]
TODO: translate to czech

**Comment by jr-rk** [comment]
All the code between < TRANSLATE THIS > < / TRANSLATE THIS > is translated, except the bitstream fields - 2 fields on top, 1 on bottom (of commented area)
