### ISSUE TITLE
internal/improve-build-process

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#84]
Building the DSpace takes too long, check building process in the pom.xml and decide if building process could be faster.

Slack conversation where I asked how to improve building process: 
![image](https://user-images.githubusercontent.com/90026355/178237120-c89e53f5-e6ec-47db-b779-7da769fdffd7.png)

**Comment by MajoBerger** [comment]
Use 
`mvn install -Dmaven.compiler.compilerArgs=-Xpkginfo:always`
to avoid useless recompilation. Will later add to .pom, possibly from upstream. 
Explanation in our MS Teams.
