### ISSUE TITLE
internal/create wiki for Clarin-DSpace installation process

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#93]
Sometimes we add some configurations, properties,.. and we cannot forget what we need to configure. Create wiki page when will be this installation process. Clarin-DSpace wiki could be inspiration: https://github.com/ufal/clarin-dspace/wiki

**Comment by MajoBerger** [comment]
@milanmajchrak If you already had such necessities, please add to [installation wiki](https://github.com/dataquest-dev/DSpace/wiki/Installation)
